services:
  frontend:
    image: frontend:1.0.0
    container_name: frontend
    build: ./frontend
    ports:
      - "3000:3000"
    restart: always

  backend:
    image: backend:1.0.0
    container_name: backend
    build: ./backend
    restart: always