services:
  nginx:
    image: nginx
    build:
      context: ./services/nginx
      dockerfile: Dockerfile
    container_name: nginx
    networks:
      - main_net
    env_file:
      - .env
    ports:
      - "443:443"
      - "9090:9090"
    volumes:
      - certs:/certs
      - grafana-certs:/certs/grafana-certs
      - certs-ca:/certs/ca
      - grafana-conf:/usr/share/grafana/conf/provisioning/datasources

  nextjs:
    container_name: nextjs
    image: nextjs
    build:
      context: ./frontend
    networks:
      - main_net

  game-service:
    container_name: game-service
    image: game-service:1.0.0
    build:
      context: ./services/game-service
    networks:
      - main_net

  # user-service:
  #   container_name: user-service
  #   image: user-service:v2.0.0
  #   build:
  #     context: ./services/user-service
  #   networks:
  #     - main_net

  # chat-service:
  #   container_name: chat-service
  #   image: chat-service:v2.0.0
  #   build:
  #     context: ./services/chat-service
  #   networks:
  #     - main_net

networks:
  main_net:
    name: main_net

  
volumes:
  certs:
  grafana-certs:
  certs-ca:
  grafana-conf:

